CREATE TABLE t_products (
    prod_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_title VARCHAR2(100) NOT NULL,
    book_price NUMBER(10, 2) DEFAULT 0 NOT NULL,
	book_quantity NUMBER DEFAULT 0,
	prod_added_on DATE DEFAULT TRUNC(sysdate) NOT NULL
);


alter table t_products add constraint chk_book_price  CHECK (book_price > 0);
alter table t_products add constraint chk_book_quantity  CHECK (book_quantity >= 0);