CREATE TABLE t_customers (
    cust_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    email_off VARCHAR2(30) UNIQUE NOT NULL,
    email_personal VARCHAR2(30),
    family_mem NUMBER DEFAULT 0 NOT NULL,
	created_on DATE DEFAULT TRUNC(sysdate) NOT NULL
);

alter table t_customers add constraint chk_family_mem CHECK (family_mem >= 0);